github:
  is_project_page: false

theme: jekyll-theme-hacker
title: Aidan Comi's Coding Projects
description: See all the cool new projects Aidan has built.

pages_list:
  contact: '/contact'
  testpage: '/testpage'

google_analytics: G-EM5RJ1VBGH
