theme: jekyll-theme-hacker
title: Aidan Comi Dev Projects
description: Some projects I've created, not really anything advanced, but wanted to keep track.

pages_list:
  contact: '/contact'

github:
  is_project_page: false
